version: "2"

services:
  web:
    image: testweb
    depends_on:
      - db
    links:
      - db:mysql
    volumes:
      - /home/ec2-user/infotect/modules:/var/www/html/modules
      - /home/ec2-user/infotect/override:/var/www/html/override
      - /home/ec2-user/infotect/themes:/var/www/html/themes
      - /home/ec2-user/infotect/1617:/var/www/html/1617
      - /home/ec2-user/infotect/img:/var/www/html/img
    ports:
      - "80:80"
    environment:
      - PS_HANDLE_DYNAMIC_DOMAIN=1
      - PS_DOMAIN=54.236.206.140

  db:
    image: testdb
    volumes:
     - /home/ec2-user/infotect/base:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=Tamara2021@
