version: "2"

services:
  web:
    build:
      dockerfile: Dockerfile
      context: ./
    depends_on:
      - db
    environment:
      - PS_DEV_MODE=0
    links:
      - db:mysql
    volumes:
      - /home/ec2-user/infotect/1617:/var/www/html/1617
      - /home/ec2-user/infotect/modules:/var/www/html/modules
      - /home/ec2-user/infotect/override:/var/www/html/override
      - /home/ec2-user/infotect/themes:/var/www/html/themes
      - /home/ec2-user/infotect/img:/var/www/html/img
    ports:
      - "80:80"

  db:
    image: mysql
    volumes:
     - /home/ec2-user/infotect/base:/var/lib/mysql
    environment:
     MYSQL_ROOT_PASSWORD: Tamara2021@
